[package]
name = "spwn"
version = "0.1.0"
edition = "2024"

[dependencies]
iced = { version = "0.14.0", features = ["tokio"] }
shell-words = "1.1.1"
tokio = { version = "1.49.0", features = ["full"] }
